// One-off, READ-ONLY: compares the live dbo.PageDefinitions table against
// scripts/data/used-page-keys.txt (generated by scanUsedPageKeys.js from
// the real frontend usePageRights()/pageKey and backend requirePageRight()
// call sites) to find:
//
//   1. Orphaned rows: PageKey is IsActive=1 in the DB but nothing in the
//      current codebase checks it anymore — a leftover from a rename,
//      consolidation, or removed feature. These show up as grantable
//      toggles in Menu Rights that do nothing when granted.
//   2. Gaps: a key the code actually checks has no PageDefinitions row at
//      all (or only an inactive one) — that page can never be granted
//      through Menu Rights no matter what an admin toggles.
//
// Unlike the frontend/backend source scan (which needs the full repo
// checked out), THIS script only needs a DB connection, so it runs fine
// inside the production backend container — it just reads the checked-in
// used-page-keys.txt rather than re-scanning source at runtime. Re-run
// scanUsedPageKeys.js locally and commit the refreshed file whenever pages
// are added/removed/renamed.
//
// Usage: node scripts/findOrphanedPageDefinitions.js
const fs = require("fs");
const path = require("path");
const { connectDB, getPool, closeDB } = require("../db");

// Known-legitimate exceptions — investigated in the "is every page in the
// project in Page Permissions / Menu Rights" audit this session. These
// genuinely have zero usePageRights()/pageKey/requirePageRight reference
// anywhere, but that's by design, not a bug, in one of three ways:
//   - Gated by ROLE, not a per-page grant (AdminRoute/SuperAdminRoute
//     checks role membership directly; the PageDefinitions row is
//     display-only and toggling it in Menu Rights has no effect either
//     way): admin-control-panel, metrics-dashboard, superadmin-profile.
//   - The Home landing page — every logged-in user lands here, no gate
//     needed: dashboard.
//   - A pure redirect route (Navigate), nothing to gate: crm-communication.
//   - External-portal pages under separate portal auth (RequireAuth only),
//     not part of internal staff RBAC at all: supplier-catalog,
//     supplier-quotations.
// Re-verify this list stays accurate whenever it's touched — it is NOT a
// blanket "ignore forever" list, just the specific keys already checked.
const KNOWN_EXCEPTIONS = new Set([
  "admin-control-panel",
  "metrics-dashboard",
  "superadmin-profile",
  "dashboard",
  "crm-communication",
  "supplier-catalog",
  "supplier-quotations",
]);

async function main() {
  const usedKeysFile = path.join(__dirname, "data", "used-page-keys.txt");
  if (!fs.existsSync(usedKeysFile)) {
    console.error(`Missing ${usedKeysFile} — run scripts/scanUsedPageKeys.js locally first and commit its output.`);
    process.exit(1);
  }
  const usedKeys = new Set(
    fs.readFileSync(usedKeysFile, "utf8").split("\n").map((s) => s.trim()).filter(Boolean),
  );
  console.log(`Loaded ${usedKeys.size} used page keys from ${usedKeysFile}\n`);

  await connectDB();
  const pool = getPool();
  const result = await pool.request().query(`
    SELECT PageKey, Label, Module, IsActive FROM dbo.PageDefinitions ORDER BY PageKey
  `);

  const activeRows = result.recordset.filter((r) => r.IsActive);
  const orphaned = activeRows.filter(
    (r) => !usedKeys.has(r.PageKey) && !KNOWN_EXCEPTIONS.has(r.PageKey),
  );

  console.log(`=== Active PageDefinitions rows with no code reference: ${orphaned.length} ===`);
  for (const r of orphaned) {
    console.log(`  ${r.PageKey}  (Label="${r.Label}", Module="${r.Module}")`);
  }
  if (orphaned.length > 0) {
    console.log("\n-- Suggested cleanup (deactivate, don't delete — keeps history):");
    console.log(
      `  UPDATE dbo.PageDefinitions SET IsActive = 0 WHERE PageKey IN (${orphaned
        .map((r) => `'${r.PageKey}'`)
        .join(", ")});`,
    );
  }

  const dbKeys = new Set(result.recordset.map((r) => r.PageKey));
  const activeDbKeys = new Set(activeRows.map((r) => r.PageKey));
  const gaps = [...usedKeys].filter((k) => !activeDbKeys.has(k)).sort();
  console.log(`\n=== Code checks a key with no active PageDefinitions row: ${gaps.length} ===`);
  for (const k of gaps) {
    console.log(`  ${k}${dbKeys.has(k) ? "  (row exists but IsActive=0)" : "  (no row at all)"}`);
  }

  await closeDB();
}

main().catch((err) => {
  console.error("Scan failed:", err);
  process.exit(1);
});
