CREATE TABLE dbo.PageDefinitions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PageKey NVARCHAR(100) NOT NULL UNIQUE,
    Label NVARCHAR(150) NOT NULL,
    ModuleName NVARCHAR(100) NOT NULL,
    GroupName NVARCHAR(100) NOT NULL,
    Actions NVARCHAR(255) NOT NULL,
    SortOrder INT DEFAULT 0,
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- Seed existing page definitions so the transition is seamless
INSERT INTO dbo.PageDefinitions (PageKey, Label, ModuleName, GroupName, Actions, SortOrder, IsActive)
VALUES 
('dashboard', 'Dashboard', 'General', 'Dashboard', 'view,export', 10, 1),
('finance-dashboard', 'Finance Dashboard', 'Finance', 'Finance & Accounts', 'view,print,export', 20, 1),
('bank-master', 'Bank Master', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 30, 1),
('account-head', 'Account Head Master', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 40, 1),
('account-group', 'Account Group', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 50, 1),
('general-ledger', 'General Ledger', 'Finance', 'Finance & Accounts', 'view,print,export', 60, 1),
('expense-booking', 'Expense Booking', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 70, 1),
('new-payment', 'Payments', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 80, 1),
('received-payment', 'Received Payment', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 90, 1),
('cheque-master', 'Cheque Master', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 100, 1),
('brs', 'Bank Reconciliation', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 110, 1),
('debit-note', 'Debit Note', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 120, 1),
('amendments', 'Amendments', 'Finance', 'Finance & Accounts', 'view,create,edit,delete,print,export', 130, 1),
('material-dashboard', 'Material Dashboard', 'Material', 'Material', 'view,print,export', 140, 1),
('purchase-orders', 'Purchase Orders', 'Material', 'Material', 'view,create,edit,delete,print,export', 150, 1),
('grn-master', 'GRN Master', 'Material', 'Material', 'view,create,edit,delete,print,export', 160, 1),
('work-order', 'Work Order', 'Material', 'Material', 'view,create,edit,delete,print,export', 170, 1),
('material-request', 'Material Request', 'Material', 'Material', 'view,create,edit,delete,print,export', 180, 1),
('material-issues', 'Material Issues', 'Material', 'Material', 'view,create,edit,delete,print,export', 190, 1),
('stock-ledger', 'Stock Ledger', 'Material', 'Material', 'view,print,export', 200, 1),
('stock-transfers', 'Stock Transfers', 'Material', 'Material', 'view,create,edit,delete,print,export', 210, 1),
('inventory-master', 'Inventory Master', 'Material', 'Material', 'view,create,edit,delete,print,export', 220, 1),
('engineering-dashboard', 'Engineering Dashboard', 'Engineering', 'Engineering', 'view,print,export', 230, 1),
('boq', 'BOQ', 'Engineering', 'Engineering', 'view,create,edit,delete,print,export', 240, 1),
('engineering-work-order', 'Work Order (Eng)', 'Engineering', 'Engineering', 'view,create,edit,delete,print,export', 250, 1),
('work-done', 'Work Done', 'Engineering', 'Engineering', 'view,create,edit,delete,print,export', 260, 1),
('followup-dashboard', 'Follow-Up Dashboard', 'Follow-Up', 'Follow-Up', 'view,print,export', 270, 1),
('followup-applicants', 'Applicants', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 280, 1),
('followup-bookings', 'Bookings', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 290, 1),
('followup-agreements', 'Agreements', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 300, 1),
('followup-unit-selection', 'Unit Selection', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 310, 1),
('followup-noc', 'NOC', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 320, 1),
('followup-sales-deed', 'Sales Deed', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 330, 1),
('followup-handover', 'Handover', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 340, 1),
('followup-construction', 'Construction Updates', 'Follow-Up', 'Follow-Up', 'view,create,edit,delete,print,export', 350, 1),
('tickets', 'Tickets', 'Ticket', 'Tickets', 'view,create,edit,delete,print,export', 360, 1),
('ticket-resolution', 'Ticket Resolution', 'Ticket', 'Tickets', 'view,edit', 370, 1),
('item-master', 'Item Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 380, 1),
('item-group', 'Item Group', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 390, 1),
('hsn-master', 'HSN Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 400, 1),
('enterprise-master', 'Enterprise / Company', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 410, 1),
('project-master', 'Project Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 420, 1),
('contractor-master', 'Contractor Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 430, 1),
('supplier-master', 'Supplier Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 440, 1),
('customer-master', 'Customer Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 450, 1),
('uom-master', 'UOM Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 460, 1),
('activity-master', 'Activity Master', 'Masters', 'Masters', 'view,create,edit,delete,print,export', 470, 1),
('reports', 'Reports', 'General', 'Reports', 'view,print,export', 480, 1),
('tasks', 'Tasks', 'General', 'Tasks & Widgets', 'view,create,edit,delete', 490, 1),
('widgets', 'Widgets', 'General', 'Tasks & Widgets', 'view', 500, 1),
('approval-inbox', 'Approval Inbox', 'General', 'Tasks & Widgets', 'view,edit', 510, 1);
GO