import { toast } from "sonner";

type PreviewField = {
  label: string;
  value?: string | number | boolean | null;
};

type PreviewSection = {
  title: string;
  fields: PreviewField[];
};

type PrintPreviewOptions = {
  title: string;
  subtitle: string;
  code?: string | null;
  status?: string | null;
  logo?: string | null;
  sections: PreviewSection[];
};

const escapeHtml = (value: unknown) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const display = (value: PreviewField["value"]) => {
  if (value === true) return "Yes";
  if (value === false) return "No";
  if (value === null || value === undefined || value === "") return "—";
  return String(value);
};

export function printMasterPreview({
  title,
  subtitle,
  code,
  status,
  logo,
  sections,
}: PrintPreviewOptions) {
  const logoHtml = logo
    ? `<img src="${escapeHtml(logo)}" alt="Logo" style="height:58px;max-width:180px;object-fit:contain;" />`
    : `<span style="font-size:20px;font-weight:800;color:#4f46e5;">Civilier ERP</span>`;

  const sectionsHtml = sections
    .map(
      (section) => `
        <div class="section">
          <div class="section-title">${escapeHtml(section.title)}</div>
          <div class="grid">
            ${section.fields
              .map(
                (field) => `
                  <div class="field">
                    <label>${escapeHtml(field.label)}</label>
                    <span>${escapeHtml(display(field.value))}</span>
                  </div>`,
              )
              .join("")}
          </div>
        </div>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(subtitle)} — ${escapeHtml(title || code || "")}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #111827; background: #fff; padding: 36px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 20px; border-bottom: 2px solid #4f46e5; margin-bottom: 26px; gap: 24px; }
    .doc-block { text-align: right; }
    .doc-title { font-size: 24px; font-weight: 800; color: #4f46e5; letter-spacing: -0.5px; }
    .doc-name { font-size: 15px; font-weight: 700; color: #111827; margin-top: 5px; }
    .doc-code { font-size: 12px; font-family: monospace; color: #6b7280; margin-top: 4px; }
    .badge { display: inline-block; margin-top: 8px; padding: 4px 10px; border-radius: 999px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; background: #eef2ff; color: #4338ca; }
    .section { margin-bottom: 22px; page-break-inside: avoid; }
    .section-title { font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.1em; color: #4f46e5; margin-bottom: 10px; padding-bottom: 5px; border-bottom: 1px solid #e0e7ff; }
    .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px 16px; }
    .field { min-width: 0; }
    .field label { display: block; margin-bottom: 3px; color: #9ca3af; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; }
    .field span { display: block; color: #111827; font-size: 12px; font-weight: 500; line-height: 1.5; overflow-wrap: anywhere; }
    .footer { margin-top: 36px; padding-top: 14px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; font-size: 11px; color: #9ca3af; }
    @media print {
      body { padding: 16px; }
      button { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>${logoHtml}</div>
    <div class="doc-block">
      <div class="doc-title">${escapeHtml(subtitle)}</div>
      <div class="doc-name">${escapeHtml(title || "—")}</div>
      ${code ? `<div class="doc-code">${escapeHtml(code)}</div>` : ""}
      ${status ? `<span class="badge">${escapeHtml(status)}</span>` : ""}
    </div>
  </div>
  ${sectionsHtml}
  <div class="footer">
    <span>Generated by CivilierERP</span>
    <span>Printed: ${new Date().toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    })}</span>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const blobUrl = URL.createObjectURL(blob);
  const win = window.open(blobUrl, "_blank", "width=960,height=720");
  if (!win) {
    URL.revokeObjectURL(blobUrl);
    toast.error("Pop-up blocked — please allow pop-ups for this site.");
    return;
  }
  setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
  win.onload = () => {
    win.focus();
    win.print();
  };
}
