-- Migration: Add rich targeting and creative fields to SaAd
-- Transforms SaAd from a basic budget tracker into a full-fledged ad campaign manager
-- with targeting, scheduling, creative asset management, and external platform linking.

-- Creative / Copy fields
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'Headline')
BEGIN
  ALTER TABLE dbo.SaAd ADD Headline NVARCHAR(300) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'Description')
BEGIN
  ALTER TABLE dbo.SaAd ADD Description NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'CtaText')
BEGIN
  ALTER TABLE dbo.SaAd ADD CtaText NVARCHAR(100) NULL;
END;

-- Creative asset URLs
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'ImageUrl')
BEGIN
  ALTER TABLE dbo.SaAd ADD ImageUrl NVARCHAR(2000) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'VideoUrl')
BEGIN
  ALTER TABLE dbo.SaAd ADD VideoUrl NVARCHAR(2000) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'MediaUrls')
BEGIN
  ALTER TABLE dbo.SaAd ADD MediaUrls NVARCHAR(MAX) NULL;
END;

-- Targeting fields
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetAgeMin')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetAgeMin INT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetAgeMax')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetAgeMax INT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetGender')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetGender NVARCHAR(20) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetLocations')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetLocations NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetRadiusKm')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetRadiusKm DECIMAL(10, 2) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetInterests')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetInterests NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetBehaviors')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetBehaviors NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'TargetLanguages')
BEGIN
  ALTER TABLE dbo.SaAd ADD TargetLanguages NVARCHAR(500) NULL;
END;

-- Scheduling
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'ScheduledStartAt')
BEGIN
  ALTER TABLE dbo.SaAd ADD ScheduledStartAt DATETIME2 NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'ScheduledEndAt')
BEGIN
  ALTER TABLE dbo.SaAd ADD ScheduledEndAt DATETIME2 NULL;
END;

-- External platform linking
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'ExternalAdId')
BEGIN
  ALTER TABLE dbo.SaAd ADD ExternalAdId NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'ExternalAdSetId')
BEGIN
  ALTER TABLE dbo.SaAd ADD ExternalAdSetId NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'PlatformPlacement')
BEGIN
  ALTER TABLE dbo.SaAd ADD PlatformPlacement NVARCHAR(500) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'Objective')
BEGIN
  ALTER TABLE dbo.SaAd ADD Objective NVARCHAR(100) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'OptimizationGoal')
BEGIN
  ALTER TABLE dbo.SaAd ADD OptimizationGoal NVARCHAR(100) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'BidStrategy')
BEGIN
  ALTER TABLE dbo.SaAd ADD BidStrategy NVARCHAR(100) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'DestinationUrl')
BEGIN
  ALTER TABLE dbo.SaAd ADD DestinationUrl NVARCHAR(2000) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'UtmParameters')
BEGIN
  ALTER TABLE dbo.SaAd ADD UtmParameters NVARCHAR(MAX) NULL;
END;

-- Sync metadata
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'LastSyncedAt')
BEGIN
  ALTER TABLE dbo.SaAd ADD LastSyncedAt DATETIME2 NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaAd' AND COLUMN_NAME = 'SyncStatus')
BEGIN
  ALTER TABLE dbo.SaAd ADD SyncStatus NVARCHAR(30) NULL;
END;

GO

-- Index for external ad lookup
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SaAd_ExternalAdId')
BEGIN
  CREATE INDEX IX_SaAd_ExternalAdId ON dbo.SaAd(ExternalAdId)
    WHERE ExternalAdId IS NOT NULL;
END;
