-- Migration: Add detailed source attribution fields to SaLead
-- Keeps exact external lead/ad form/UTM/raw payload details for CRM attribution.

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'ExternalLeadId')
BEGIN
  ALTER TABLE dbo.SaLead ADD ExternalLeadId NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'LeadFormName')
BEGIN
  ALTER TABLE dbo.SaLead ADD LeadFormName NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'SourceCampaignName')
BEGIN
  ALTER TABLE dbo.SaLead ADD SourceCampaignName NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'SourceAdName')
BEGIN
  ALTER TABLE dbo.SaLead ADD SourceAdName NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'SourcePlacement')
BEGIN
  ALTER TABLE dbo.SaLead ADD SourcePlacement NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'LeadCaptureUrl')
BEGIN
  ALTER TABLE dbo.SaLead ADD LeadCaptureUrl NVARCHAR(2000) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'UtmSource')
BEGIN
  ALTER TABLE dbo.SaLead ADD UtmSource NVARCHAR(100) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'UtmMedium')
BEGIN
  ALTER TABLE dbo.SaLead ADD UtmMedium NVARCHAR(100) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'UtmCampaign')
BEGIN
  ALTER TABLE dbo.SaLead ADD UtmCampaign NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'UtmContent')
BEGIN
  ALTER TABLE dbo.SaLead ADD UtmContent NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'UtmTerm')
BEGIN
  ALTER TABLE dbo.SaLead ADD UtmTerm NVARCHAR(200) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'CapturedAt')
BEGIN
  ALTER TABLE dbo.SaLead ADD CapturedAt DATETIME2(3) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SaLead' AND COLUMN_NAME = 'SourcePayload')
BEGIN
  ALTER TABLE dbo.SaLead ADD SourcePayload NVARCHAR(MAX) NULL;
END;

GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SaLead_ExternalLeadId')
BEGIN
  CREATE INDEX IX_SaLead_ExternalLeadId ON dbo.SaLead(ExternalLeadId)
    WHERE ExternalLeadId IS NOT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SaLead_SourceChain')
BEGIN
  -- SourceType is intentionally excluded here: it is added later by
  -- migration 147-crm-enhancements.sql, which runs after this file.
  CREATE INDEX IX_SaLead_SourceChain ON dbo.SaLead(PlatformId, CampaignId, AdId)
    INCLUDE (DateGenerated, Status, CustomerName, Mobile);
END;
