-- Migration 151: Add line items to DebitNote

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DebitNote' AND COLUMN_NAME = 'DocNo'
)
  ALTER TABLE dbo.DebitNote ADD DocNo NVARCHAR(50) NULL;

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DebitNote' AND COLUMN_NAME = 'DebitDate'
)
  ALTER TABLE dbo.DebitNote ADD DebitDate DATE NULL;

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DebitNote' AND COLUMN_NAME = 'Reason'
)
  ALTER TABLE dbo.DebitNote ADD Reason NVARCHAR(1000) NULL;

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DebitNote' AND COLUMN_NAME = 'TotalAmount'
)
  ALTER TABLE dbo.DebitNote ADD TotalAmount DECIMAL(18,2) NULL;

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DebitNote' AND COLUMN_NAME = 'Status'
)
  ALTER TABLE dbo.DebitNote ADD Status NVARCHAR(20) NOT NULL DEFAULT 'Draft';

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DebitNoteItems')
BEGIN
  CREATE TABLE dbo.DebitNoteItems (
    ItemId        INT IDENTITY(1,1) PRIMARY KEY,
    DebitNoteId   INT NOT NULL REFERENCES dbo.DebitNote(id),
    Description   NVARCHAR(500) NOT NULL,
    Quantity      DECIMAL(18,4) NULL,
    UOMSymbol     NVARCHAR(30)  NULL,
    Rate          DECIMAL(18,4) NULL,
    Amount        DECIMAL(18,2) NULL
  );
END;
